import React from "react";
import Hero from "../../components/Hero";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

const sectionHeading = "text-2xl md:text-4xl font-['Balsamiq_Sans'] text-[#E68C8C]";

const definitionItems = [
    {
        title: "Account",
        desc: "A unique account created for You to access our Service or parts of our Service."
    },
    {
        title: "Application",
        desc: "The software program provided by the Company downloaded by You on any device"
    },
    {
        title: "Company",
        desc: "The Company is Refers to as Raisingright.Education, Mumbai 47, MH."
    },
    {
        title: "Personal Data",
        desc: "Any information that relates to an identified or identifiable individual."
    },
    {
        title: "Usage Data",
        desc: "Data collected automatically, generated by the use of Service or the infrastructure itself."
    },
    {
        title: "Service",
        desc: "Refers to as Application"
    }
];

const collectingCards = [
    {
        title: "Personal Data",
        desc: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You"
    },
    {
        title: "School Context",
        desc: "Data visible on the Application is collected within School premises by our Staff only for the purpose of creating visibility over a child's growth."
    },
    {
        title: "Usage Data",
        desc: "Collected automatically when using the Service, including Your Device's IP address, browser type, pages visited, and time spent on those pages."
    }
];

const usagePoints = [
    "To provide and maintain our Service, including monitoring usage.",
    "To manage Your Account and registration as a user.",
    "For the performance of a contract for products or services purchased.",
    "To contact You via email, telephone, SMS, or push notifications regarding updates or security.",
    "To provide news and offers about similar goods and services unless You opt out.",
    "For business transfers, such as evaluating a merger or sale of assets."
];

const retentionCards = [
    {
        title: "Retention",
        desc: "We retain Your Personal Data only for as long as necessary for the purposes set out in this policy or to comply with legal obligations"
    },
    {
        title: "Security",
        desc: "While We strive to use commercially acceptable means to protect Your Personal Data, remember that no method of transmission over the Internet is 100% secure."
    }
];

const FrameImage = ({ desktop, mobile, alt = "frame" }) => (
    <>
        <img src={desktop} alt={alt} className="absolute inset-0 w-full h-full object-fill pointer-events-none hidden md:block" />
        <img src={mobile} alt={alt} className="absolute inset-0 w-full h-full object-fill pointer-events-none md:hidden" />
    </>
);

const PrivacyPolicy = () => {
    return (
        <section className="min-h-screen w-full bg-[#FFFAEE] text-gray-900">
            <Header />

            <Hero
                bgImage="/pnp.png"
                mobileBgImage="/mpnp.png"
                tag=""
                title={<>Privacy Policy</>}
                description="Protecting every child's and parent's information with care, trust, and complete transparency."
            />

            <div className="max-w-screen-xl mx-auto py-16 px-6 md:py-24 md:px-8 space-y-16 md:space-y-20">

                <div className="relative w-full">
                    <FrameImage desktop="/pnp1.png" mobile="/mpnp1.png" />
                    <div className="relative p-8 md:p-16 text-center">
                        <h2 className={`${sectionHeading} mb-6 md:mb-8`}>
                            Last Updated : May 24, 2025
                        </h2>
                        <p className="font-['Balsamiq_Sans'] font-medium text-xl max-w-4xl mx-auto leading-relaxed md:leading-[2]">
                            This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                        </p>
                    </div>
                </div>

                {/* Interpretation and Definitions */}
                <div className="text-center">
                    <h2 className={`${sectionHeading} mb-10 md:mb-12`}>
                        Interpretation and Definitions
                    </h2>
                    <div className="grid gap-6 md:grid-cols-3 md:gap-8">
                        {definitionItems.map((item, i) => (
                            <div key={i} className="relative">
                                <FrameImage desktop="/pnp2.png" mobile="/mpnp2.png" />
                                <div className="relative p-6 md:p-8 text-left">
                                    <h3 className="font-['Balsamiq_Sans'] font-[500] text-lg md:text-xl text-black mb-2">
                                        {item.title}
                                    </h3>
                                    <p className="font-['Poppins'] text-sm md:text-base text-gray-600 leading-[2.2] md:leading-[1.8]">
                                        {item.desc}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Collecting and Using Your Personal Data */}
                <div className="text-center">
                    <h2 className={`${sectionHeading} mb-10 md:mb-12`}>
                        Collecting and Using Your Personal Data
                    </h2>
                    <div className="grid gap-6 md:grid-cols-3 md:gap-8">
                        {collectingCards.map((item, i) => (
                            <div key={i} className="relative">
                                <FrameImage desktop="/tnc3.png" mobile="/mpnp3.png" />
                                <div className="relative p-6 md:p-8 text-center">
                                    <h3 className="font-['Poppins'] font-semibold text-lg text-[#31A6AE] mb-3 md:mb-4">
                                        {item.title}
                                    </h3>
                                    <p className="font-['Poppins'] text-sm md:text-base leading-[2] md:leading-[1.8]">
                                        {item.desc}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Use of Your Personal Data */}
                <div className="relative w-full mt-16 md:mt-20">
                    <FrameImage desktop="/tnc4.png" mobile="/mpnp4.png" />
                    <div className="relative p-8 md:p-16 max-w-4xl mx-auto">
                        <h2 className={`${sectionHeading} text-center mb-6 md:mb-8`}>
                            Use of Your Personal Data
                        </h2>
                        <p className="font-['Balsamiq_Sans'] font-medium text-lg md:text-2xl text-black mb-6 leading-relaxed md:leading-[1.9]">
                            The Company may use Personal Data for the following purposes:
                        </p>
                        <ul className="space-y-3 max-w-2xl mx-auto text-left">
                            {usagePoints.map((point, i) => (
                                <li key={i} className="flex items-start gap-2 font-['Poppins'] text-sm md:text-base text-gray-700 leading-[2.2] md:leading-[1.9]">
                                    <span className="mt-[2px]">•</span>
                                    <span>{point}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>

                {/* Data Retention and Security */}
                <div className="text-center">
                    <h2 className={`${sectionHeading} mt-16 md:mt-20 mb-10 md:mb-12`}>
                        Data Retention and Security
                    </h2>
                    <div className="grid gap-6 md:grid-cols-2 md:gap-10">
                        {retentionCards.map((item, i) => (
                            <div key={i} className="relative">
                                <FrameImage desktop="/tnc5.png" mobile="/mpnp5.png" />
                                <div className="relative p-6 md:p-8">
                                    <h3 className="font-['Balsamiq_Sans'] font-semibold text-lg md:text-xl text-black text-left mb-3 md:mb-4">
                                        {item.title}
                                    </h3>
                                    <p className="font-['Poppins'] text-sm md:text-base text-gray-600 text-left leading-[2] md:leading-[1.9]">
                                        {item.desc}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Children's Privacy */}
                <div className="relative w-full mt-16 md:mt-20">
                    <FrameImage desktop="/tnc6.png" mobile="/mpnp6.png" />
                    <div className="relative p-8 md:p-10 text-center max-w-3xl mx-auto">
                        <h2 className={`${sectionHeading} mb-6 md:mb-8`}>
                            Children's Privacy
                        </h2>
                        <p className="font-['Poppins'] font-medium text-sm md:text-base text-gray-600 leading-[2] md:leading-[2.4]">
                            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If We become aware that We have collected data from a child under 13 without parental consent, We take steps to remove that information.
                        </p>
                    </div>
                </div>

            </div>
            <Footer />
        </section>
    );
};

export default PrivacyPolicy;